### ISSUE TITLE
How to fix "Cannot set capture resolution" message?

### ISSUE THREAD

**Issue by WeLastO** [StanislavPetrovV/Matrix-Vision#2]
I've installed all dependences and force PC to work with videocaputre module.
But I'm unable to find solution for  "Cannot set capture resolution" message.
Please help!

I'm using Windows and Python 2.7

> Traceback (most recent call last):
  File "C:/Users/Dmitry/OneDrive/Documents/GitHub/Matrix-Vision/main.py", line 108, in <module>
    app = MatrixVision()
  File "C:/Users/Dmitry/OneDrive/Documents/GitHub/Matrix-Vision/main.py", line 90, in __init__
    self.cam = pygame.camera.Camera(camlist[0], (640, 480))
  File "C:\Python27\lib\site-packages\pygame\_camera_vidcapture.py", line 60, in __init__
    self.dev.setresolution(width, height)
vidcap.Error: Cannot set capture resolution.

**Comment by StanislavPetrovV** [comment]
about Python 2.7, I can't tell you about the problem.
The project was made on Python 3 (using Python 3.8.2, Pygame 2.0.0dev18, Numpy 1.19.2)

**Comment by forj1900** [comment]
I've installed pygame 2.0.0.dev8 (SDL 2.0.12, python 3.8.6), Numpy 1.19.2
The same issue.

Is videocapture lib required? I've tried to install in from here
https://www.lfd.uci.edu/~gohlke/pythonlibs/#videocapture

But got error
`ERROR: VideoCapture-0.9.5-cp39-cp39-win32.whl is not a supported wheel on this platform.`
same with amd64.whl image

**Comment by StanislavPetrovV** [comment]
pip install videocapture

**Comment by wisrovi** [comment]
tengo el mismo problema, esta muy bueno la meta a lograr pero tambien tengo el mensaje "No se puede establecer la resolución de captura", he instalado los paquetes en sus versiones correspondientes, he probado con python 3.6, 3.7 y 3.8 , con maquina virtual y sin maquina virtual, pero aún no logro que funcione

Me podrias guiar para validar que he hecho mal?

Gracias

**Comment by vlasvlasvlas** [comment]
here having the same issue.
